import { useEffect, useState } from "react";
import { api } from "../api/client";

export function AiExplanationDrawer({
  runId,
  cachedExplanation,
  onClose,
  onExplained,
}: {
  runId: number;
  cachedExplanation: string | null;
  onClose: () => void;
  onExplained: (text: string) => void;
}) {
  const [explanation, setExplanation] = useState<string | null>(cachedExplanation);
  const [loading, setLoading] = useState(cachedExplanation === null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (explanation !== null) return; // already have it (cached from the run row)
    let cancelled = false;
    setLoading(true);
    api
      .explainRun(runId)
      .then((res) => {
        if (cancelled) return;
        setExplanation(res.explanation);
        onExplained(res.explanation);
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [runId]);

  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      <button
        aria-label="Close"
        onClick={onClose}
        className="absolute inset-0 bg-surface/80 backdrop-blur-sm"
      />
      <div className="relative flex h-full w-full max-w-md flex-col overflow-y-auto border-l border-surface-container-high bg-surface-container-low shadow-2xl">
        <div className="flex items-center justify-between border-b border-surface-container-high p-4">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-primary">auto_awesome</span>
            <div>
              <h3 className="text-sm font-semibold text-on-surface">AI Explanation</h3>
              <p className="font-mono text-[11px] text-on-surface-variant">Google Gemini</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1 text-on-surface-variant hover:text-on-surface">
            <span className="material-symbols-outlined text-base">close</span>
          </button>
        </div>

        <div className="flex-1 p-4">
          {loading && (
            <div className="space-y-2">
              <div className="h-3 w-full animate-pulse rounded bg-surface-container-highest" />
              <div className="h-3 w-5/6 animate-pulse rounded bg-surface-container-highest" />
              <div className="h-3 w-4/6 animate-pulse rounded bg-surface-container-highest" />
              <div className="h-3 w-full animate-pulse rounded bg-surface-container-highest" />
            </div>
          )}

          {error && (
            <div className="rounded border border-error/40 bg-error-container/20 p-3 text-sm text-error">
              Couldn't get an explanation: {error}
              <p className="mt-2 text-xs text-on-surface-variant">
                If this is the first time, make sure the backend has a Gemini API key configured (see
                backend/README.md).
              </p>
            </div>
          )}

          {!loading && !error && explanation && (
            <p className="whitespace-pre-line text-sm leading-relaxed text-on-surface">{explanation}</p>
          )}
        </div>

        <div className="border-t border-surface-container-high p-4 font-mono text-[11px] text-on-surface-variant">
          Generated by AI from this run's variant summary — a simplified explanation, not a clinical
          interpretation. This is synthetic demo data.
        </div>
      </div>
    </div>
  );
}
